# action.yaml
name: 'Healing'
author: Alex
description: 'Description'
inputs:
  openai-key:
    description: 'The OpenAI API key'
    required: true

runs:
  using: 'composite'
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13.0-alpha.4'
        cache: 'pipenv'
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - run: pipenv install

    - name: Run code snippet
      run: |
        pipenv run python healing.py "${{ inputs.openai-key }}"
      env:
        OPENAI_API_KEY: ${{ inputs.openai-key }}

branding:
  icon: 'user-check'
  color: 'green'
